# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

# Packages! tbd...

# Constants and variables!
# Set the upper limit that the sequence must not exceed
term_limit = 4000000
# term_limit = 10

# Define the 'summer' containing the running of sums
summer = 0

# Functions!
def main():
    global summer
    term = 0
    term_1 = 1
    term_2 = 0

    while term < term_limit:

        term = term_1 + term_2

        if term % 2 == 0:
            summer = summer + term

        term_2 = term_1
        term_1 = term

    print(summer)


if __name__ == "__main__":
    main()
